apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespaces/namespace.yaml
  - 01-boutique/release-complete.yaml
  - 02-dashboard/01-headlamp.yaml
  - 03-monitoring/01-prometheus.yaml
  - 03-monitoring/02-kube-state-metrics.yaml
  - 03-monitoring/03-grafana.yaml
